version: 0.2

phases:
    build:
        commands:
            - echo 'Building Services App............'
            - mvn -Pamazon clean package
        
artifacts:
    files: target/cloudservices/**/*
    discard-paths: yes
    
cache:
  paths:
    - '/root/.m2/**/*'
